### ISSUE TITLE
A plugin from V 0.62 cause crashes in Ubuntu 22.04/Reaper

### ISSUE THREAD

**Issue by ryukau** [ryukau/VSTPlugins#54]
This issue opened from the linked comment on another issue.

https://github.com/ryukau/VSTPlugins/issues/35#issuecomment-2379895132_

**Comment by ryukau** [comment]
@maxxatgit Are you using the plugins from zip file on the release page, or built from source code?

Probably the plugins in zip files only work on Ubuntu 24.04. I set `ubuntu-latest` on GitHub Actions, and it seems like the Ubuntu version is updated recently. I updated documentations in commit [688f7f3](https://github.com/ryukau/VSTPlugins/commit/688f7f36ad85ca6a6c35afaeaff044f3ff11df02).

- [Choosing the runner for a job - GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories)

**Comment by maxxatgit** [comment]
Yes, I'm using the plugins from the zip file.

**Comment by ryukau** [comment]
Yes, it's possible. Instructions are below.

1. Fork this repository on GitHub.
2. Clone the forked repository to your local.
3. Replace the content of `.github/workflows/build.yml`.
4. Trigger GitHub Actions.

On step 3, delete all texts in the original `build.yml`, and replace to following. Click "Details" below to display the code.

<details>

```yaml
on: push

env:
  package_path: package

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04  # Ubuntu version can be set here.
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run script
      run: ci/ci_ubuntu.sh
    - name: Upload
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: vst_ubuntu
        path: vst_ubuntu
```

</details>

On step 4, following commands trigger GitHub Action. Assuming that the remote name is set as `origin`.

```bash
git add -A
git commit --allow-empty -m ""
git push -u origin master
```

After the workflow is completed, you can find the plugins in a bit deep in Action tab in your forked repository.

I will not setup the build for older versions of OSes, because I once got a warning related to the storage limit on GitHub.
